[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
btc-htlc = { path = "../agent/btc" }

bitcoin = { workspace = true }
bitcoincore-rpc = "0.19"

ethers = "2.0"
alloy-primitives = "1.3"

tokio = { version = "1.0", features = ["full"] }

serde = { workspace = true }
serde_json = "1.0"

anyhow = "1.0"
thiserror = { workspace = true }

clap = { version = "4.0", features = ["derive"] }

hex = "0.4"
rand = "0.9"
uuid = { version = "1.0", features = ["v4"] }

tracing = "0.1"
tracing-subscriber = "0.3"

chrono = { version = "0.4", features = ["serde"] }
