[package]
name = "client"
version = "0.1.0"
edition = "2024"
default-run = "main"

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "derive_privkey"
path = "src/bin/derive_privkey.rs"

[dependencies]
btc-htlc = { path = "../agent/btc" }
bitcoin = { workspace = true }
bitcoincore-rpc = "0.19"
ethers = "2.0"
# alloy-primitives = "1.3"
hex = { workspace = true }
tokio = { version = "1.0", features = ["full"] }
serde = { workspace = true }
serde_json = "1.0"
sha2 = { workspace = true }
anyhow = "1.0"
thiserror = { workspace = true }
clap = { version = "4.0", features = ["derive"] }
rand = "0.8"
# uuid = { version = "1.0", features = ["v4"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt"] }
chrono = { version = "0.4", features = ["serde"] }
