[package]
name = "sol-htlc"
version = "0.1.0"
description = "Hash Time Locked Contract (HTLC) for Solana"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "sol_htlc"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build"]


[dependencies]
anchor-lang = { version = "0.31.1", features = ["init-if-needed"] }
anchor-spl = { version = "0.31.1", features = ["metadata"] }
mpl-token-metadata = "5.1.1"

[dev-dependencies]
solana-program-test = "3.0.0"
solana-sdk = "3.0.0"
tokio = "1.0"
