[workspace]
members = ["btc"]

resolver = "3"

[workspace.dependencies]
bitcoin = { version = "0.32", features = ["serde", "rand"] }
serde = { version = "1.0", features = ["derive"] }
thiserror = "2.0.15"
