services:
  bitcoin:
    build: .
    platform: linux/amd64
    container_name: xchain-btc
    command: >
      bitcoind -regtest 
      -server=1 
      -rpcallowip=0.0.0.0/0 
      -rpcbind=0.0.0.0:18443 
      -rpcuser=user 
      -rpcpassword=password 
      -fallbackfee=0.0001 
      -txindex=1 
      -blockfilterindex=1 
      -peerbloomfilters=1 
      -printtoconsole
    ports:
      - "18443:18443"
      - "18444:18444"
    volumes:
      - bitcoin-data:/app/.bitcoin
    networks:
      - xchain-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "18443"]
      interval: 5s
      timeout: 3s
      retries: 12

  ethereum:
    build: .
    platform: linux/amd64
    container_name: xchain-eth
    working_dir: /app/agent/eth
    command: >
      bash -c "
        rm -rf node_modules &&
        npm install --silent &&
        npx hardhat compile &&
        npx hardhat node --hostname 0.0.0.0 --port 8545
      "
    ports:
      - "8545:8545"
    volumes:
      - eth-artifacts:/app/agent/eth/artifacts
      - eth-deployments:/app/agent/eth/ignition/deployments
    networks:
      - xchain-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8545"]
      interval: 5s
      timeout: 3s
      retries: 12

  solana:
    build: .
    platform: linux/amd64
    container_name: xchain-sol
    command: start-solana.sh
    ports:
      - "8899:8899"
      - "8900:8900"
    volumes:
      - solana-data:/app/.solana-ledger
    networks:
      - xchain-network
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "8899"]
      interval: 15s
      timeout: 10s
      retries: 30

  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: xchain-app
    command: >
      bash -c "./docker-setup.sh"
    volumes:
      - .:/app
      - bitcoin-data:/app/.bitcoin
      - eth-artifacts:/app/agent/eth/artifacts
      - eth-deployments:/app/agent/eth/ignition/deployments
      - solana-data:/app/.solana-ledger
    depends_on:
      bitcoin:
        condition: service_healthy
      ethereum:
        condition: service_healthy
      solana:
        condition: service_started
    networks:
      - xchain-network
    environment:
      - BTC_RPC_URL=http://bitcoin:18443
      - ETH_RPC_URL=http://ethereum:8545
      - SOL_RPC_URL=http://solana:8899

volumes:
  bitcoin-data:
  eth-artifacts:
  eth-deployments:
  solana-data:

networks:
  xchain-network:
    driver: bridge
