[package]
name = "btc-htlc"
description = "Hash Time Locked Contract (HTLC) for Bitcoin"
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { workspace = true }
thiserror = { workspace = true }
rand = "0.9"
