[package]
name = "btc-htlc"
description = "Hash Time Locked Contract (HTLC) for Bitcoin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
bitcoin = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
sha2 = { workspace = true }

rand = "0.8"
